# Generated by Django 5.0.6 on 2024-07-08 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=240)),
                ('skills', models.TextField()),
                ('link', models.TextField()),
                ('repo_link', models.TextField()),
                ('image', models.TextField(blank=True, null=True)),
                ('project_ui', models.CharField(choices=[('normal', 'normal'), ('detailed', 'detailed'), ('simple', 'simple')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='PortfolioStudyCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=50)),
                ('project_description', models.TextField()),
                ('project_workflow', models.TextField()),
                ('project_link', models.TextField()),
                ('project_repo', models.TextField()),
                ('work_time', models.CharField(choices=[('1-3 weeks', '1-3 weeks'), ('1 month', '1 month'), ('2-3 months', '2-3 months'), ('3-6 months', '3-6 months')], default=('1-3 weeks', '1-3 weeks'), max_length=50)),
                ('chosen', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50)),
                ('skills', models.TextField()),
                ('aggregative_project', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
